dist: trusty

language: php

php:
  - 7.1

before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY
  - composer require --dev magento/magento-coding-standard
  - composer install

script:
  - vendor/bin/phpcs --ignore=./vendor/*,./magento-coding-standard/*,./Test/* --standard=Magento2 --extensions=php,phtml,js .
